// constants/routes.ts
export const routes = {
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  TAB_NAVIGATOR: 'TAB_NAVIGATOR',
  
  DASHBOARD_TAB: 'DASHBOARD_TAB',
  HELP_TAB: 'HELP_TAB',

  DASHBOARD_SCREEN: 'DASHBOARD_SCREEN',
  HELP_SCREEN: 'HELP_SCREEN',
  SECURITY_SCREEN: 'SECURITY_SCREEN',
} as const;