export const routes = {
    //tabs
    HOME_TAB: 'HOME_TAB',
    FAQS_TAB: 'FAQS_TAB',
    FEEDBACK_TAB: 'FEEDBACK_TAB',
    TAB_NAVIGATOR: 'TAB_NAVIGATOR',
    //app
    SPLASH_SCREEN: 'SPLASH_SCREEN',
    ONBOARDING_SCREEN: 'ONBOARDING_SCREEN',
    ESIM_INSTALLATION_SCREEN: 'MY_SIM_SCREEN',
    INTRO_SCREEN: 'CHOOSE_OPTION_SCREEN',
    VERIFY_EMAIL_SCREEN: 'VERIFY_EMAIL_SCREEN',
} as const;
